### ISSUE TITLE
start development command

### ISSUE THREAD

**Issue by SpectreMercury** [Flouse/ckb-academy#45]
- To start the project, you need to run `yarn dev:site` command. 
- In Vite, you can add 
```
server: {
    open: true
}
``` 
in the configuration file, which will automatically open the page when starting the development server. If the page is already opened in the browser, it will switch to that page automatically. Note that you may need project permissions to commit the changes.

**Comment by oriole-pub** [comment]
Can you create a PR to add this section of content to the readme?

**Comment by SpectreMercury** [comment]
> Can you create a PR to add this section of content to the readme?

Hi Jason,

Here is the [PR](https://github.com/Flouse/ckb-academy/pull/46) of this issue
