### ISSUE TITLE
Code in web container not updating live after file changes

### ISSUE THREAD

**Issue by Flouse** [Flouse/ckb-academy#69]
![image](https://github.com/Flouse/ckb-academy/assets/1297478/e3e9aba3-5e73-4b08-9797-80307072f05c)

Although files are changed, but the code in the webcontainer is not updated live.

_Originally posted by @Flouse in https://github.com/Flouse/ckb-academy/issues/66#issuecomment-1649589897_

**Comment by oriole-pub** [comment]
Please try using `command+s` to save the file so that the file changes can be synchronized to the webContainer.

**Comment by Flouse** [comment]
> Please try using `command+s` to save the file so that the file changes can be synchronized to the webContainer.

You are right. It's not a bug.

**Comment by Flouse** [comment]
- related issue: https://github.com/codemirror/codemirror5/issues/3628
